# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bac69d28ef76d8d31687ab1f4969fbc4b4671db97fc04fd0fcef51ef9c7dc5b4656e9831a518e18a8aa3ecd0b110d3de27ea8075c644ef6b17c825af0cb9cd2

test:
  secret_key_base: 660f87aad83122c88c7d1715ec9a54b4d5db5809d76746489aadde32547ff7bb84f476dbede68d60ba3bd8b4e522864f0ed6262ee8fc97f03f1cce9c28bca660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
